FROM python:3.6

RUN apt update -y && apt upgrade -y && apt install -y python3-pip jq
RUN pip3 install requests pyghmi kubernetes beautifulsoup4
WORKDIR /opt/torpedo
COPY entrypoint.sh entrypoint.sh
RUN /bin/bash entrypoint.sh
COPY plugins/orchestrator/torpedo_orchestrator /opt/torpedo/
CMD ["/bin/bash"]
