FROM python:3.6

RUN apt update -y && apt upgrade -y && apt install -y python3-pip
RUN pip3 install requests kubernetes
WORKDIR /opt/torpedo
COPY entrypoint.sh entrypoint.sh
RUN /bin/bash entrypoint.sh
COPY plugins/chaos/torpedo_chaos /opt/torpedo/
ENV KUBECONFIG=/root/.kube/config
CMD ["/bin/bash"]
